# Base configs
baseurl: ""
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "images/fulls"
image_thumbs_loc: "images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Justyou"
subtitle: "See the world through my eyes!"
author: "Justyou"
header:
 title: "Photography"
 subtitle: "by 柚you"
footer:
 name: "Hey there, my name is Luo"
 bio: "I am a student from China,enjoying photography."
web_design: "AJ"

social_urls:
  instagram: "https://www.instagram.com/yo.uyou9232/"
  notebook: "https://www.xiaohongshu.com/user/profile/67c3b907000000001703cf72"
  mipai: "https://mipai.com.cn/photographer/u_68ca87778b804"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
